### ISSUE TITLE
Test scenes error when loaded on Godot 4.0.3

### ISSUE THREAD

**Issue by KeltonHislop** [don-tnowe/godot-wyvernbox-inventory#2]
#### Description
The test_2d.tscn, test_3d.tscn, and inventory_menu.tscn scenes give errors when one attempts to add them to the scene tree or double click to open them. This was tested on Godot 4.0.3 and Godot 4.0.3 .NET version. Behavior persists regardless of where in the scene tree the tscn is added. 
#### Screenshots
![image](https://github.com/don-tnowe/godot-wyvernbox-inventory/assets/36969519/503ce82c-ac30-49bc-a037-8d01fb155704)
#### To Reproduce
* Add Wyvernbox files to the resources directory of a new project
* Create new scene with a root node
* Attempt to add test_2d.tscn to scene tree as a child of root node
-----
* Add Wyvernbox files to the resources directory of a new project
* Double click test_2d.tscn
#### Files
est_2d.tscn, test_3d.tscn, and inventory_menu.tscn

**Comment by don-tnowe** [comment]
Thank you for a detailed and formatted report!

I can't really fix this. This issue happens because paths in scene files are absolute (*e.g. "res://example/graphics/font.ttf" not "<current folder>/graphics/font.ttf"*) I see in your FS dock the `example` and `addons` folders are in a sub-folder `godot-wyvernbox-inventory`, not in the root directory - try:

- just moving these two out of it and into under `res://`;
- opening the `project.godot` file inside the folder you cloned.
 
This is mainly Godot's problem, missing dependency resolution is broken in 4.0 right now, so it no longer lets you fix it at all, let alone with one click :/

**Comment by WithinAmnesia** [comment]
Also what is the main scene and like why do all the scenes crash when played? I have it working sorta? 
![image](https://github.com/don-tnowe/godot-wyvernbox-inventory/assets/86871191/569ecf26-a356-4034-8066-4498f0c3c608)
It looks good but it looks to not be running quite right. What should be done here? Any ideas hey?
